/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdActivityRouteImport } from './routes/_app.projects.$projectId.activity'
import { Route as AppProjectsProjectIdOverviewRouteImport } from './routes/_app.projects.$projectId.overview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdActivityRoute =
  AppProjectsProjectIdActivityRouteImport.update({
    id: '/projects/$projectId/activity',
    path: '/projects/$projectId/activity',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdOverviewRoute =
  AppProjectsProjectIdOverviewRouteImport.update({
    id: '/projects/$projectId/overview',
    path: '/projects/$projectId/overview',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/_app/projects/$projectId/overview': typeof AppProjectsProjectIdOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/projects/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/projects'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/overview'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/profile'
    | '/_app/projects/'
    | '/_app/projects/$projectId/activity'
    | '/_app/projects/$projectId/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/activity': {
      id: '/_app/projects/$projectId/activity'
      path: '/projects/$projectId/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof AppProjectsProjectIdActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/overview': {
      id: '/_app/projects/$projectId/overview'
      path: '/projects/$projectId/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof AppProjectsProjectIdOverviewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdActivityRoute: typeof AppProjectsProjectIdActivityRoute
  AppProjectsProjectIdOverviewRoute: typeof AppProjectsProjectIdOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdActivityRoute: AppProjectsProjectIdActivityRoute,
  AppProjectsProjectIdOverviewRoute: AppProjectsProjectIdOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
